Accept exp and nbf in ms
crystal-community/jwt pull request #8
Opened 2017-08-26 19:26 UTC by solisoft

Some JWT tokens contains time fields in ms instead of seconds and it raise an error.

This PR just convert time in seconds if needed and validate then the token

2017-08-30 09:13 UTC, veelenga commented on examples/basic_usage.cr
> +pp header
Your example does not work for me:

```sh
$ cr examples/basic_usage.cr                                                                                                                                                     
token # => "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmb28iOiJiYXIifQ.Y3shN5Wh4FmOPM34biIm9QQmat373hJFKNxgSANQWJo"
payload # => {"foo" => "bar"}
header # => {"typ" => "JWT", "alg" => "HS256"}
Signature is expired (JWT::ExpiredSignatureError)
0x1028dd6c5: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1028dd661: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1028dd638: *CallStack::new:CallStack at ??
0x1028dc495: *raise<JWT::ExpiredSignatureError>:NoReturn at ??
0x102936e38: *JWT@JWT::validate_exp!<(Array(JSON::Type) | Bool | Float64 | Hash(String, JSON::Type) | Int64 | String | Nil)>:Nil at ??
0x102936aac: *JWT@JWT::decode<String, String, String>:Tuple(Hash(String, JSON::Type), Hash(String, JSON::Type)) at ??
0x1028c7857: __crystal_main at ??
0x1028dafc8: main at ??

```

2017-08-30 19:35 UTC, solisoft commented
Well this is because the token has expire :)

2017-08-30 19:36 UTC, solisoft commented
But at least it stop raising the int32 error

2017-08-30 20:22 UTC, veelenga commented
@solisoft yes, but that means this example is just useless. Could you please add two tests instead for the following cases:

```crystal
# positive case
token = JWT.encode({"foo" => "bar", "exp" => Time.now.epoch + 1}, "SecretKey", "HS256")
JWT.decode(token, "SecretKey", "HS256") # payload is successfully decoded

# negative case
token = JWT.encode({"foo" => "bar", "exp" => Time.now.epoch - 1}, "SecretKey", "HS256")
JWT.decode(token, "SecretKey", "HS256") # JWT::ExpiredSignatureError is raised
```

2017-08-30 20:23 UTC, veelenga requested changes
@solisoft yes, but that means this example is just useless. Could you please add specs instead for the following cases:

```crystal
# positive case
token = JWT.encode({"foo" => "bar", "exp" => Time.now.epoch_ms + 1000}, "SecretKey", "HS256")
JWT.decode(token, "SecretKey", "HS256") # payload is successfully decoded

# negative case
token = JWT.encode({"foo" => "bar", "exp" => Time.now.epoch_ms - 1000}, "SecretKey", "HS256")
JWT.decode(token, "SecretKey", "HS256") # JWT::ExpiredSignatureError is raised
```

2017-08-31 13:56 UTC, solisoft commented
Ok Actually I thinjk we can remove this PR because it's a bug from arangodb token generator ... not this lib.
https://github.com/arangodb/arangodb/issues/2249

2017-08-31 13:56 UTC, closed without merging

2017-08-31 14:07 UTC, veelenga commented
Hm, okay, so only seconds should be supported...